development:
  adapter: postgresql
  encoding: unicode
  database: serviceorder_development
  username: Admin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: serviceorder_test
  username: Admin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: serviceorder
  username: Admin
  password: